export enum RouteChannel {
    INDEX = '/',
    R403 = 'unauthorized',
    R404 = "*",
    FORGOT_PASSWORD='/forgot-password',
    SIGN_UP = '/sign-up',
    DASHBOARD = '/a',
    SETTINGS = '/settings',
    NOTIFICATIONS = '/notifications',
    PROFIFLE = '/profile/:Id',
    CONTACTS = '/contacts',
    PROJECTS = '/projects',
    PROJECTS_DETAILS = '/projects/d/:Id',
    ABOUT = '/about',
}