export enum RouteChannel {
  INDEX = "/",
  UNDERCONSTRUCTION = "under-construction",
  R403 = "unauthorized",
  R404 = "*",
  NOT_FOUND = "/not-found",
  FORGOT_PASSWORD = "/forgot-password",
  SIGN_UP = "/sign-up",
  DASHBOARD = "/a",
  SETTINGS = "/settings",
  NOTIFICATIONS = "/notifications",
  PROFIFLE = "/profile/:Id",
  CONTACTS = "/contacts",
  PROJECTS = "/projects",
  PROJECTS_DETAILS = "/projects/d/:Id",
  ABOUT = "/about",
}
